[features]
seeds = false
skip-lint = false

[programs.localnet]
openbook_dca = "6LbR2Zur89bdFiAzGeUwAZDEqcbC2mBLke1vYVPbPVYu"

[programs.devnet]
openbook_dca = "6LbR2Zur89bdFiAzGeUwAZDEqcbC2mBLke1vYVPbPVYu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/corpus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
